### PR TITLE
Added dedicated instructions for TS-464

### PR DESCRIPTION
**Pull request by MethodFox**
Had a hard time getting fan control working on TS-464. So I decided to do some research on how to make it possible to control the fan on TS-464. I have added instructions from my research into a separate markdown file so as to keep the original Readme.md clean. I didn't necessarily want to post it on the forum first, as I believe this info could also help other QNAP users who have more modern units. Hope it helps! It's also my first time doing a pull request, so let me know if I did anything wrong or need to make any edits! =)

### CODE REVIEW

**Comment by MethodFox** [comment]
Ended up modifying a small part of qnap-ec.plg, but undid that change to keep the repo and this pull request more in line with ich777's original repo. Ignore those redundant commits. Thanks!

**Comment by ich777** [comment]
Thanks for the PR, I will look into that ASAP.
Please give me at least a week, have a few things in the queue.

**Comment by ich777** [comment]
@0xFoxx if it's okay for you I will merge this in my private git and close this PR since I also have to update the plugin so that these changes appear on machines from users or do you simply want that the instructions are visible in the CA App?

**Comment by MethodFox** [comment]
> @0xFoxx if it's okay for you I will merge this in my private git and close this PR since I also have to update the plugin so that these changes appear on machines from users or do you simply want that the instructions are visible in the CA App?

Sure! Whichever way you prefer to go. Up to you. =) Not familiar with what CA App means haha.

**Comment by ich777** [comment]
@0xFoxx I've changed a bit in your doc since it will be easier that way. :)
Hope that makes perfect sense for you.

**Comment by j3n57h0m45** [comment]
I have successfully tested these instructions on a **TS-453E**. Fan speed is correctly reported and can be adjusted as described.

**Comment by turkeyphant** [comment]
@0xFoxx 

I'm having an issue where there is no "hardware status" on my dashboard.

I also have /sys/class/hwmon/hwmon0 and /sys/class/hwmon/hwmon1 but neither have any pwn entries in them.

This is with QNAP TS-EC1079 Pro.

**Comment by MethodFox** [comment]
> @0xFoxx
> 
> I'm having an issue where there is no "hardware status" on my dashboard.
> 
> I also have /sys/class/hwmon/hwmon0 and /sys/class/hwmon/hwmon1 but neither have any pwn entries in them.
> 
> This is with QNAP TS-EC1079 Pro.

Well unfortunately, I have changed to a custom built UNRAID setup at this time, so I can't be much more use here considering I sold my TS-464.

Best of luck with your pursuit though!

**Comment by ich777** [comment]
@turkeyphant I'm not sure if the QNAP TS-EC1079 Pro is even supported by the driver from @Stonyx over [here](https://github.com/Stonyx/QNAP-EC), you can create an issue there but I'm not sure if he is active anymore (I hope he is well).

**Pull request closed without merging**
